CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    actor_user_id NUMBER NULL,
    action_type VARCHAR2(100) NOT NULL,
    target_entity VARCHAR2(100) NOT NULL,
    target_entity_id VARCHAR2(100) NULL,
    details CLOB NULL,
    ip_address VARCHAR2(100) NULL
);

CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp);
CREATE INDEX idx_audit_logs_actor_user_id ON audit_logs (actor_user_id);
CREATE INDEX idx_audit_logs_action_type ON audit_logs (action_type);